name: footwere_store_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  
  cloud_firestore: ^4.15.4
  dropdown_button2: ^2.3.9
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  flutter:
    sdk: flutter
  get: ^4.6.6
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  get_storage: ^2.1.1
  otp_text_field_v2: ^1.0.3
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  

flutter:
  uses-material-design: true
